name: CI
run-name: "${{ github.event.repository.name }} | CI | ${{ github.run_id }} | ${{ github.event_name }}"
permissions: read-all

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - main
      - 'release/**'
      - 'hotfix/**'
    paths:
      - 'src/**'
      - 'tests/**'
      - 'docs/*'
      - '.github/**'
      - '*'

jobs:
  changes:
    outputs:
      src: ${{ steps.filter.outputs.src }}
      github: ${{ steps.filter.outputs.github }}
      build: ${{ steps.filter.outputs.build }}
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.01
        with:
          repository: ${{ github.repository }}

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 #v3.0.2
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
            tests:
              - 'tests/**'

      - name: Execute assign PR labels
        id: action-assign-labels
        uses: mauroalderete/action-assign-labels@v1
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commits: '.github/labeler.yml'
          apply-changes: true

  setup:
    name: Setup
    uses: WarehouseFinds/PSScriptModule/.github/workflows/powershell-script-module-cache-dependencies.yml@main
    if: > 
      needs.changes.outputs.src == 'true' ||
      needs.changes.outputs.tests == 'true'

  unit-tests:
    name: Unit Tests
    needs: [setup]
    uses: WarehouseFinds/PSScriptModule/.github/workflows/powershell-script-module-analysis-unit-tests.yml@main
    permissions:
      issues: write
      pull-requests: write
      checks: write
    with:
      module-list: ${{ needs.setup.outputs.module-list }}
    if: needs.changes.outputs.src == 'true'

  static-code-analysis:
    name: Static Code Analysis
    needs: [setup]
    uses: WarehouseFinds/PSScriptModule/.github/workflows/powershell-script-module-analysis-static-code.yml@main
    permissions:
      issues: write
      pull-requests: write
      checks: write
    with:
      module-list: ${{ needs.setup.outputs.module-list }}
    if: > 
      needs.changes.outputs.src == 'true' ||
      needs.changes.outputs.tests == 'true'

  code-injection:
    name: Code Injection
    needs: [setup]
    uses: WarehouseFinds/PSScriptModule/.github/workflows/powershell-script-module-analysis-code-injection.yml@main
    permissions:
      issues: write
      pull-requests: write
      checks: write
    with:
      module-list: ${{ needs.setup.outputs.module-list }}
    if: > 
      needs.changes.outputs.src == 'true' ||
      needs.changes.outputs.tests == 'true'

  semantic-code-analysis:
    name: Semantic Code Analysis
    needs: [setup]
    uses: WarehouseFinds/PSScriptModule/.github/workflows/powershell-script-module-analysis-codeQL.yml@main
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read
    if: needs.changes.outputs.src == 'true'


  build:
    name: Build
    needs: [setup, unit-tests, static-code-analysis, code-injection, semantic-code-analysis]
    uses: WarehouseFinds/PSScriptModule/.github/workflows/powershell-script-module-build.yml@main
    permissions:
      contents: write
    with:
      release-type: 'Debug'
      module-list: ${{ needs.setup.outputs.module-list }}
    if: >
      needs.unit-tests.result == 'skipped' ||
      needs.unit-tests.result == 'success'