name: CI
run-name: CI • ${{ github.repository }} • ${{ github.event_name }} • ${{ github.ref_name }}
permissions: read-all

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release Type [Release/Prerelease/Debug]'
        required: true
        default: Release
        type: choice
        options:
          - Release
          - Prerelease
          - Debug

      publish:
        description: 'Publish release to PSGallery (Release only)'
        required: false
        type: boolean
        default: false
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/help/**'
  pull_request:
    branches:
      - main
      - 'release/**'
      - 'hotfix/**'

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/ps-cache-dependencies.yml

  unit-tests:
    name: Unit Tests
    needs: [setup]
    uses: ./.github/workflows/ps-unit-tests.yml
    permissions:
      issues: write
      pull-requests: write
      checks: write
    with:
      module-list: ${{ needs.setup.outputs.module-list }}

  static-code-analysis:
    name: Static Code Analysis
    needs: [setup]
    uses: ./.github/workflows/ps-static-code-analysis.yml
    permissions:
      issues: write
      pull-requests: write
      checks: write
    with:
      module-list: ${{ needs.setup.outputs.module-list }}

  code-injection:
    name: Code Injection
    needs: [setup]
    uses: ./.github/workflows/ps-code-injection.yml
    permissions:
      issues: write
      pull-requests: write
      checks: write
    with:
      module-list: ${{ needs.setup.outputs.module-list }}

  semantic-code-analysis:
    name: Semantic Code Analysis
    needs: [setup]
    uses: ./.github/workflows/ps-semantic-code-analysis.yml
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read
  
  build:
    name: Build
    needs: [setup, unit-tests, static-code-analysis]
    uses: ./.github/workflows/ps-build-module.yml
    permissions:
      contents: write
    with:
      release-type: ${{ inputs.release-type || 'Release' }}
      publish: ${{ inputs.publish || false }}
      module-list: ${{ needs.setup.outputs.module-list }}