name: Cleanup
run-name: "${{ github.event.repository.name }} | Cleanup | ${{ github.run_id }} | ${{ github.event_name }}"
on:
  schedule:
    # Every day at midnight
    - cron: '0 0  * * *'
  workflow_dispatch:
    inputs:
      retain-days:
        description: 'Number of days to retain workflow runs'
        required: false
        type: number
        default: 2
      minimum-runs:
        description: 'Minimum number of recent workflow runs to retain'
        required: false
        type: number
        default: 2
        

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs (CI workflows)
        uses: Mattraks/delete-workflow-runs@5bf9a1dac5c4d041c029f0a8370ddf0c5cb5aeb7  #v2.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: ci.yml
          retain_days: ${{ github.event.inputs.retain-days || 2 }}
          keep_minimum_runs: ${{ github.event.inputs.minimum-runs || 2 }}
          check_pullrequest_exist: true

      - name: Delete workflow runs (Release workflows)
        uses: Mattraks/delete-workflow-runs@5bf9a1dac5c4d041c029f0a8370ddf0c5cb5aeb7  #v2.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: release.yml
          retain_days: ${{ github.event.inputs.retain-days || 2 }}
          keep_minimum_runs: ${{ github.event.inputs.minimum-runs || 2 }}
          check_pullrequest_exist: true

      - name: Delete workflow runs (Scheduled cleanup runs)
        uses: Mattraks/delete-workflow-runs@5bf9a1dac5c4d041c029f0a8370ddf0c5cb5aeb7  #v2.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: cleanup.yml
          retain_days: ${{ github.event.inputs.retain-days || 1 }}
          keep_minimum_runs: ${{ github.event.inputs.minimum-runs || 1 }}

      - name: Delete workflow runs (Copilot code reviews)
        uses: Mattraks/delete-workflow-runs@5bf9a1dac5c4d041c029f0a8370ddf0c5cb5aeb7  #v2.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: copilot | Copilot
          retain_days: ${{ github.event.inputs.retain-days || 1 }}
          keep_minimum_runs: ${{ github.event.inputs.minimum-runs || 1 }}