name: Cron • Cleanup past artifacts
run-name: ${{ github.event_name }} • Cleanup past artifacts • ${{ github.repository }}

on:
  schedule:
    # Every day at midnight
    - cron: '0 0 * * *'

jobs:
  cleanup-past-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: write

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@44fc7acaf1b3d0987da0e8d4707a989d80e9554b #v1.4.0
      with:
        age: '2 days'
        # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        # Optional inputs
        # skip-tags: true
        skip-recent: 2