name: CI
run-name: "${{ github.event.repository.name }} | CI | ${{ github.run_id }} | ${{ github.event_name }}"
permissions: read-all

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'

  pull_request:
    branches:
      - main
      - 'release/**'
      - 'hotfix/**'
    paths:
      - 'src/**'
      - 'tests/**'
      - 'docs/**'
      - '.github/**/*'
      - '*'

jobs:
  changes:
    name: Label Changes
    runs-on: [ubuntu-latest]
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Labeler
      id: labeler
      uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b #v6.0.1

  setup:
    name: Setup
    uses: .github/workflows/ps-resolve-dependencies.yml

  unit-tests:
    name: Unit Tests
    needs: [setup]
    uses: .github/workflows/ps-analysis-unit-tests.yml
    permissions:
      issues: write
      pull-requests: write
      checks: write
    with:
      module-list: ${{ needs.setup.outputs.module-list }}

  static-code-analysis:
    name: Static Code Analysis
    needs: [setup]
    uses: .github/workflows/ps-analysis-static-code.yml
    permissions:
      issues: write
      pull-requests: write
      checks: write
    with:
      module-list: ${{ needs.setup.outputs.module-list }}

  code-injection:
    name: Code Injection
    needs: [setup]
    uses: .github/workflows/ps-analysis-code-injection.yml
    permissions:
      issues: write
      pull-requests: write
      checks: write
    with:
      module-list: ${{ needs.setup.outputs.module-list }}

  semantic-code-analysis:
    name: Semantic Code Analysis
    needs: [setup]
    uses: .github/workflows/ps-analysis-codeQL.yml
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read

  build:
    name: Build
    needs: [setup, unit-tests, static-code-analysis, code-injection, semantic-code-analysis]
    uses: .github/workflows/ps-build.yml
    permissions:
      contents: write
    with:
      release-type: 'Debug'
      module-list: ${{ needs.setup.outputs.module-list }}