name: Release
run-name: "${{ github.event.repository.name }} | Release | ${{ github.run_id }} | ${{ github.event_name }}"
permissions: read-all

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Prerelease
      publish-psgallery:
        description: 'Publish release to PSGallery'
        required: false
        type: boolean
        default: true
      publish-nugetorg:
        description: 'Publish release to NuGet.org'
        required: false
        type: boolean
        default: false

jobs:
  setup:
    name: Setup
    uses: .github/workflows/ps-resolve-dependencies.yml

  build:
    name: Build
    needs: [setup]
    uses: .github/workflows/ps-build.yml
    permissions:
      contents: write
    with:
      release-type: ${{ inputs['release-type'] }}
      module-list: ${{ needs.setup.outputs.module-list }}

  release:
    name: Release
    needs: [setup, build]
    uses: .github/workflows/ps-release.yml
    permissions:
      contents: write
    with:
      release-type: ${{ inputs['release-type'] }}
      release-version: ${{ needs.build.outputs.release-version }}
      publish-psgallery: ${{ inputs.publish-psgallery }}
      publish-nugetorg: ${{ inputs.publish-nugetorg }}
      module-list: ${{ needs.setup.outputs.module-list }}
    secrets: inherit
