name: Release
run-name: "${{ github.event.repository.name }} | Release | ${{ github.run_id }} | ${{ github.event_name }}"
permissions: read-all

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Prerelease
      publish-psgallery:
        description: 'Publish release to PSGallery'
        required: false
        type: boolean
        default: true
      publish-nugetorg:
        description: 'Publish release to NuGet.org'
        required: false
        type: boolean
        default: false

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      module-list: ${{ steps.resolve.outputs.module-list }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Resolve dependencies
        id: resolve
        uses: ./.github/actions/ps-resolve-dependencies

  build:
    name: Build
    needs: [setup]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release-version: ${{ steps.build.outputs.release-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build Module
        id: build
        uses: ./.github/actions/ps-build
        with:
          release-type: ${{ inputs['release-type'] }}
          module-list: ${{ needs.setup.outputs.module-list }}

  release:
    name: Release
    needs: [setup, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    with:
      release-type: ${{ inputs['release-type'] }}
      release-version: ${{ needs.build.outputs.release-version }}
      publish-psgallery: ${{ inputs.publish-psgallery }}
      module-list: ${{ needs.setup.outputs.module-list }}
    secrets: inherit
    steps:
      - name: Release Module
        uses: ./.github/actions/ps-release
        with:
          release-type: ${{ inputs['release-type'] }}
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          release-version: ${{ needs.build.outputs.release-version }}
          publish-psgallery: ${{ inputs.publish-psgallery }}
          publish-nugetorg: ${{ inputs.publish-nugetorg }}
          module-list: ${{ needs.setup.outputs.module-list }}
        env:
          PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
