name: Release
run-name: Release • ${{ github.repository }} • ${{ github.event_name }} • ${{ github.ref_name }}
permissions: read-all

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Prerelease
      publish-psgallery:
        description: 'Publish release to PSGallery'
        required: false
        type: boolean
        default: true
      publish-nugetorg:
        description: 'Publish release to NuGet.org'
        required: false
        type: boolean
        default: false

jobs:
  setup:
    name: Setup
    uses: WarehouseFinds/PSScriptModule/.github/workflows/powershell-script-module-cache-dependencies.yml@main

  build:
    name: Build
    needs: [setup]
    uses: WarehouseFinds/PSScriptModule/.github/workflows/powershell-script-module-build.yml@main
    permissions:
      contents: write
    with:
      module-list: ${{ needs.setup.outputs.module-list }}

  release:
    name: Release
    needs: [setup, build]
    uses: WarehouseFinds/PSScriptModule/.github/workflows/powershell-script-module-release.yml@main
    permissions:
      contents: write
    with:
      release-type: ${{ inputs['release-type'] }}
      publish-psgallery: ${{ inputs.publish-psgallery }}
      publish-nugetorg: ${{ inputs.publish-nugetorg }}
      module-list: ${{ needs.setup.outputs.module-list }}
    secrets:
      PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
      NUGETORG_API_KEY: ${{ secrets.NUGETORG_API_KEY }}