name: CI Status
run-name: '${{ github.run_id }} - CI Status - ${{ github.ref_name }}'
permissions: read-all
on:
  push:

jobs:
  status:
    name: Setup
    runs-on: ubuntu-latest

    steps:  
      - name: Initialize Status
        run: echo "CI Status Initialized"
